booktrain/routes/web.php
<?php
use App\Models\User;
use App\Models\Libro;
use App\Models\Pedido;
use App\Models\Colegio;
use App\Models\Notificacion;
use App\Models\LibrosColegios;
use App\Models\ReferenciaPedido;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BbvaController;
use App\Http\Controllers\ColegioController;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\MercadoPagoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/actualiza_fecha_envio', 'EnvioController@funcionActualizaFechaEnvioConUpdatedAt');

Route::get('/tabla_ejemplo', function () {
    return view('public.tabla_ejemplo');
});

Route::get('/tickets_ejemplo', function () {
    return view('public.tikets_ejemplo');
});

Route::get('/new_superadmin/{id}', 'UsuariosController@new_superadmin');

// Ruta para obtener csrf para hacer pruebas en postman
Route::get('/csrf', function () {
    return csrf_token();
});
Route::get('/phpinfo', function () {
    return date("Y-m-d H:i:s");
    // phpinfo();
});

// prueba de notificacion de pedido
Route::get('/notificacion_pedido/{pedido}', 'PedidoController@notificacionPedido');
//temrina prueba de notificacion de pedido

// prueba de notificacion de pedido
Route::get('/notificacion_veryfy', 'UsuariosController@notificacionEmail');
//temrina prueba de notificacion de pedido

Route::get('email/verify/{id}/{hash}', [AuthController::class, 'verify'])->name('verification.verify');
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');

// Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

// Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');
// Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');
// Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');
// Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');
// Route::post('generator_builder/generate-from-file', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile')->name('io_generator_builder_generate_from_file');
/*
*/
/** Ruta index */

Route::get('/', function () {
    return view('public.login');
})->middleware('guest')->name('root');

/** Fin ruta index */

/** Inicio rutas registro */
Route::get('/registro', function () {
    return view('public.register');
})->name('registro');

Route::post('/registro', 'AuthController@postRegister');
/** Fin rutas registro */

/** Incio rutas recuperar contraseñas */

Route::get('/recuperar', 'Auth\ForgotPasswordController@getEmail')->name('recuperar');
Route::post('/recuperar', 'Auth\ForgotPasswordController@postEmail');


Route::get('/reset-password/{token}', 'Auth\ResetPasswordController@getPassword')->name('reset_password');
Route::get('/reset-password', 'Auth\ResetPasswordController@getExpired');
Route::post('/reset-password', 'Auth\ResetPasswordController@updatePassword');

Route::get('/descargar_factura/{accion}/{id}', 'PedidoController@imprimirFactura')->name('imprimir_factura');

/** Incio rutas login */

Route::get('/login', [AuthController::class, 'getLogin'])->name('login');
Route::post('/login', [AuthController::class, 'postLogin']);

/** Fin rutas login */


/** Inicio rutas protegidas */
Route::group(['middleware' => 'auth'], function () {
    // Ruta inicio
    Route::get('/email1', function () {
        return view('/emails.entregado');
    });

    Route::get('/inicio', function () {
        return view('private.home');
    })->name('inicio');

    // Ruta información usuario
    Route::get('/mi-informacion', 'UsuariosController@miInformacion')->name('mi-informacion');

    // Ruta para el carrito de compras
    Route::get('/carrito', 'PedidoController@viewCarrito')->name('carrito');

    // Ruta para recibir la uri de redirección de la pasarela de pago de bbva y proceder a consultar el estado del pago
    Route::get('/bbva/redirect', [BbvaController::class, 'redirectVpos'])->name('bbva.vpos.redirect');

    // Crea un pago y obtiene una url de redirección para que el cliente pague usando la pasarela de BBVA
    Route::post('/bbva/pagar', [BbvaController::class, 'createPayment'])->name('bbva.vpos.create');

    Route::group(['prefix' => 'openpay'], function() {
        // Crea una referencia de pago para tienda con la pasarela de pago de OpenPay
        Route::post('crearReferencia', 'OpenPayController@referenciaTienda')->name('openpay.referencia.tienda.create');
    });

    Route::get('/datos-compra/{id}', 'PedidoController@datosPedido');

    Route::get('/datos-compra/{id}/recibo', 'PedidoController@reciboReferencia');

    // Ruta mis pedidos
    Route::get('/mis-pedidos', 'PedidoController@pedidosUsuario')->name('private.user.pedidos');

    // ruta para crear nuevo caso de soporte técnico
    Route::get('/soporte', 'TicketUsuarioController@index')->name('soporte');
    Route::post('/caso', 'TicketUsuarioController@store')->name('caso');

    // Ruta logout
    Route::get('/salir', "AuthController@logOut")->name('logout');

    // Ruta detalles de compra
    Route::prefix('pedidos')->group(function () {

        Route::prefix('xls')->group(function () {
            //cargamos un excel con los pedidos entregados y regresa un json con la información de los pedidos modificados
            Route::post('uploadPedidosEntregados', 'PedidoController@uploadPedidosEntregados');

            //cargamos un excel con los pedidos que ya fueron enviados y regresa un json con la información de los pedidos modificados
            Route::post('uploadPedidosEnviados', 'PedidoController@uploadPedidosEnviados');
        });

        Route::get('{id}/pagar', 'PedidoController@getPagar')->name('pedidos.pagar');
    });

    // Rutas para el rol de Colegio
    Route::group(['prefix' => 'colegio'], function () {
        // Vista principal para el usuario con el rol Colegio
        Route::get('dashboard', 'ColegioController@dashboard')->name('colegio.dashboard');

        Route::group(['prefix' => 'reportes'], function() {

            Route::group(['prefix' => 'general'], function() {
                // Vista para generar el reporte general
                Route::get('/', 'ColegioController@reporteGeneral')->name('colegio.reportes.general');

                // Ruta para ver el reporte
                Route::post('/', 'ColegioController@postReporteGeneral');

                // Ruta para descargar el reporte
                Route::get('/descargar', 'ColegioController@postReporteGeneralDescargar');
            });

            Route::group(['prefix' => 'alumno'], function() {
                // Vista para generar el reporte por alumno
                Route::get('/', 'ColegioController@reporteAlumno')->name('colegio.reportes.alumno');

                // Ruta para ver el reporte
                Route::post('/', 'ColegioController@postReporteAlumno');

                // Ruta para descargar el reporte
                Route::get('/descargar', 'ColegioController@postReporteAlumnoDescargar');
            });
        });

        // Ruta colegio
        Route::get('{codigo}', 'ColegioController@show')->name('colegio.show');

        // Ruta para regresar la informacion del colegio
        Route::post('/informacion', 'ColegioController@informacionColegio')->name('colegio-informacion');

        // Ruta para regresar las secciones del colegio
        Route::post('/secciones', 'ColegioController@secciones');
    });

    Route::group(['prefix' => 'usuario'], function () {

        // Ruta para editar la información del usuario
        Route::post('/informacion/{id}', 'UsuariosController@update');
    });

    Route::group(['prefix' => 'tickets'], function () {

        Route::get('/', 'TicketController@index')->name('ticket.index');

        // Ruta para retornar vista con json de informacion
        Route::get('/{id}', 'TicketUsuarioController@show')->name('ticket.show');

        // Ruta para calificar ticket
        Route::put('/{id}/calificar', 'TicketUsuarioController@calificar')->name('ticket.calificar');

        // Ruta para cerrar caso
        Route::put('/{id}/cerrar', 'TicketUsuarioController@cerrar')->name('ticket.cerrar');
    });

    Route::group(['prefix' => 'cierre_caja'], function () {
        Route::get('/', 'RegistroPagoController@getReporteGananciasDiarias');
        Route::post('/print', 'RegistroPagoController@printReporteGananciasDiarias');
    });

    Route::group(['prefix' => 'cierre_del_dia'], function () {
        Route::get('/', 'ReporteController@getReporteCierreDia');
        Route::post('/print', 'ReporteController@printReporteCierreDelDia');
    });

    Route::prefix('print')->group(function () {
        Route::get('diario_pedidos', 'PedidoController@printDiarioPedios')->name('admin.pedidos.impresion');
    });

    Route::prefix('admin')->group(function () {
        Route::get('metodosPago', 'ConfiguracionController@metodosPago')->name('admin.metodos_pago');

        Route::group(['prefix' => 'devoluciones'], function () {
            Route::get('/', 'DevolucionesController@reporteDevoluciones')->name('admin.devoluciones');
        });

booktrain/app/Models/OperacionCaja.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OperacionCaja extends Model
{
    use HasFactory;

    protected $table = 'operaciones_cajas';

    protected $attributes = [
        'billete_1000' => 0,
        'billete_500' => 0,
        'billete_200' => 0,
        'billete_100' => 0,
        'billete_50' => 0,
        'billete_20' => 0,
        'conteo_monedas' => 0,
        'monto_monedas' => 0,
        'observaciones' => ''
    ];

    protected $fillable = [
        'tipo',
        'billete_1000',
        'billete_500',
        'billete_200',
        'billete_100',
        'billete_50',
        'billete_20',
        'conteo_monedas',
        'monto_monedas',
        'observaciones'
    ];

    public function caja()
    {
        return $this->belongsTo(Caja::class, 'caja_id');
    }

    public function getTotalAttribute()
    {
        $sumatoria = 0;

        $sumatoria += $this->billete_1000 * 1000;
        $sumatoria += $this->billete_500 * 500;
        $sumatoria += $this->billete_200 * 200;
        $sumatoria += $this->billete_100 * 100;
        $sumatoria += $this->billete_50 * 50;
        $sumatoria += $this->billete_20 * 20;
        $sumatoria += $this->monto_monedas;

        return $sumatoria;
    }
}

booktrain/resources/views/private/admin/almacen/pedidos/diario.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @font-face {
            font-family: 'Roboto', sans-serif;
            font-style: normal;
            font-weight: normal;
            src: url('https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap');
        }
        .rob-font {
            font-family: 'Roboto', sans-serif;
            font-size: 16px;
        }
        /*#header,
        #footer {
        position: fixed;
        left: 0;
            right: 0;
            color: #aaa;
            font-size: 0.9em;
        }
        #header {
        top: 0;
            border-bottom: 0.1pt solid #aaa;
        }
        #footer {
        bottom: 0;
        border-top: 0.1pt solid #aaa;
        }*/
        .page-number:before {
        content: "Page " counter(page);
        }
        .page-break {
            page-break-after: always;
        }

        h1 {
            color:#000;
            float:left;
            font-size:1.3em;
            margin:0 1em 0 0;
            border-radius:3px;
        }
        .box {
            padding:5px;
            /*border-bottom:1px solid #999;*/
        }
        .box .alt {
            margin:5px;
            text-align:right;
            font-size:22px;
            position:relative;
            top:5px;
        }
    </style>

</head>
<body class="rob-font">

    @foreach ($pedidos as $index => $pedido)

    <div class="box">
        <h1 style="font-size:35px;">{{ $pedido->serie . $pedido->folio }} ({{ $pedido->status }})</h1>
        <div class="alt">Fecha de orden {{ $pedido->created_at }}</div>
    </div>
    <hr>

    <h1>{{ $pedido->colegio->nombre }}</h1>
    <br>
    <hr>

    <h1>DATOS DE CONTACTO</h1>
    <br>
    <hr>
    <table style="width:100%; margin-top:10px; vertical-align: text-top;">
        <tr style="background-color:#f2f2f2; vertical-align: text-top;">
            <td style="width:100%;" colspan="2">
                <strong style="width: 100px;">NOMBRE: </strong> <span>{{ $pedido->nombre_contacto }} {{ $pedido->apellidos_contacto }}</span>
            </td>
        </tr>
        <tr style="background-color:#fcfcfc; vertical-align: text-top;">
            <td style="width:70%;">
                <strong style="width: 100px;">EMAIL: </strong> <span>{{ $pedido->user->email }}</span>
            </td>
            <td style="width:30%;">
                <strong style="width: 100px;">TEL: </strong> <span>{{ $pedido->celular_contacto }}</span>
            </td>
        </tr>
    </table>
    <hr>

    <h1>
        @if ($pedido->tipo_entrega == 1)
        ENTREGA EN COLEGIO
        @elseif (($pedido->tipo_entrega == 2))
        ENVÍO A DOMICILIO
        @elseif (($pedido->tipo_entrega == 3))
        ENTREGA PICKUP
        @endif
    </h1>
    <br>
    <hr>
    <table style="width:100%; margin-top:10px; vertical-align: text-top;">
        <!--<tr style="background-color:#fcfcfc; vertical-align: text-top;">
            <td style="text-align:center;" colspan="4">
                @if ($pedido->tipo_entrega == 1)
                <strong>ENTREGA EN COLEGIO</strong>
                @elseif (($pedido->tipo_entrega == 2))
                <strong>ENVÍO A DOMICILIO</strong>
                @elseif (($pedido->tipo_entrega == 3))
                <strong>ENTREGA PICKUP</strong>
                @else
                <strong>ENVÍO A DOMICILIO</strong>
                @endif
            </td>
        </tr>-->
        <tr style="background-color:#f2f2f2; vertical-align: text-top;">
            <td style="width:60%;" colspan="2">
                <strong style="width: 100px;">CALLE: </strong> <span>{{ is_null($pedido->direccion) ? '' : $pedido->direccion->calle }}</span>
            </td>
            <td style="width:20%;">
                <strong style="width: 100px;">NO EXT: </strong> <span>{{ is_null($pedido->direccion) ? '' : $pedido->direccion->no_exterior }}</span>
            </td>
            <td style="width:20%;">
                <strong style="width: 100px;">NO INT: </strong> <span>{{ is_null($pedido->direccion) ? '' : $pedido->direccion->no_interior }}</span>
            </td>
        </tr>
        <tr style="background-color:#fcfcfc; vertical-align: text-top;">
            <td style="width:70%;" colspan="2">
                <strong style="width: 100px;">COL: </strong> <span>{{ is_null($pedido->direccion) ? '' : $pedido->direccion->colonia }}</span>
            </td>
            <td style="width:30%;" colspan="2">
                <strong style="width: 100px;">CP: </strong> <span>{{ is_null($pedido->direccion) ? '' : $pedido->direccion->cp }}</span>
            </td>
        </tr>
        <tr style="background-color:#f2f2f2; vertical-align: text-top;">
            <td style="width:70%;" colspan="2">
                <strong style="width: 100px;">ESTADO: </strong> <span>{{ is_null($pedido->direccion) ? '' : $pedido->direccion->estado->descripcion }}</span>
            </td>
            <td style="width:30%;" colspan="2">
                <strong style="width: 100px;">MUNICIPIO: </strong> <span>{{ is_null($pedido->direccion) ? '' : $pedido->direccion->municipio->descripcion }}</span>
            </td>
        </tr>
    </table>
    <hr>

    @if (!is_null($pedido->datosFactura))
    <h1>DATOS DE FACTURACIÓN</h1>
    <br>
    <hr>
    <table style="width:100%; margin-top:10px; vertical-align: text-top;">
        <tr style="background-color:#f2f2f2; vertical-align: text-top;">
            <td style="width:70%;" colspan="2">
                <strong style="width: 100px;">RAZÓN SOCIAL: </strong> <span>{{ $pedido->datosFactura->razon_social }}</span>
            </td>
            <td style="width:30%;">
                <strong style="width: 100px;">RFC: </strong> <span>{{ $pedido->datosFactura->rfc }}</span>
            </td>
        </tr>
        <tr style="background-color:#fcfcfc; vertical-align: text-top;">
            <td style="width:100%;" colspan="3">
                <strong style="width: 100px;">EMAIL: </strong> <span>{{ $pedido->datosFactura->correo }}</span>
            </td>
        </tr>
        <tr style="background-color:#f2f2f2; vertical-align: text-top;">
            <td style="width:38%;">
                <strong style="width: 100px;">USO DE CFDI: </strong> <span>{{ $pedido->datosFactura->cfdis->codigo }}-{{ $pedido->datosFactura->cfdis->descripcion }}</span>
            </td>
            <td style="width:27%;">
                <strong style="width: 100px;">MÉTODO DE PAGO </strong> <span>{{ $pedido->datosFactura->metodo_pago }}</span>
            </td>
            <td style="width:35%;">
                <strong style="width: 100px;">FORMA DE PAGO: </strong> <span>{{ $pedido->datosFactura->forma_pago }}</span>
            </td>
        </tr>
        <tr style="background-color:#fcfcfc; vertical-align: text-top;">
            <td>
                <strong style="width: 100px;">ESTADO DEL PAGO: </strong> <span>{{ is_null($pedido->pagos()->where('status', 'SUCCESS')->first())? 'ERROR' : 'SUCCESS' }}</span>
            </td>
            <td colspan="2">
                <strong style="width: 100px;">FECHA DE PAGO: </strong> <span>{{ is_null($pedido->pagos()->where('status', 'SUCCESS')->first())? 'ERROR' : $pedido->pagos()->where('status', 'SUCCESS')->first()->created_at }}</span>
            </td>
        </tr>
    </table>
    <hr>
    @endif

    @foreach ($pedido->resumenes as $resumen)

    <div class="box" style="text-align:center;">
        <h1>{{ $resumen->paquete->nivel->nombre }} - {{ $resumen->paquete->nivel->seccion->nombre }}  &nbsp; &nbsp; | &nbsp; &nbsp; {{ $resumen->nombre_alumno}} {{ $resumen->paterno_alumno}} {{ $resumen->materno_alumno}}</h1>
    </div>
    <br/>
    <br/>
    <table style="width:100%;">
        <tr>
            <th>LIBRO</th>
            <th>ISBN</th>
            <th>PRECIO<th
        </tr>
        @foreach ($resumen->detalles as $index2 => $detalle)
        @if ($index2 % 2 == 1)
        <tr style="background-color:#fcfcfc;">
        @else
        <tr style="background-color:#f2f2f2;">
        @endif

            <td style="width:60%;">{{ $detalle->libro->nombre }} {{ $detalle->devuelto == 1 ? '(**devuelto)' : '' }}</td>
            <td style="width:20%;">{{ $detalle->libro->isbn }}</td>
            <td style="width:20%;"><label style="position:relative; float:right;">{{ number_format($detalle->precio_libro, 2) }} MXN</label></td>
        </tr>
        @endforeach
    </table>
    @endforeach

    <br/>
    <table style="width:30%; position:relative; float:right;">
        <tr style="background-color:#f2f2f2;">
            <td><strong style="position:relative; float:right;">SUBTOTAL: </strong>  </td>
            <td style="text-align: right;"><label>{{ number_format($pedido->resumenes->sum('subtotal'), 2) }} MXN</label></td>
        </tr>
        <tr style="background-color:#fcfcfc;">
            <td><strong style="position:relative; float:right;">ENVIO: </strong>  </td>
            <td style="text-align: right;">{{ $pedido->tipo_entrega == 2 && !is_null($pedido->envio) ? number_format($pedido->envio->costo, 2) : number_format(0, 2) }} MXN</td>
        </tr>
        <tr style="background-color:#f2f2f2;">
            <td><strong style="position:relative; float:right;">COMISION: </strong>  </td>
            <td style="text-align: right;">{{ number_format($pedido->comision, 2) }} MXN</td>
        </tr>
        <tr style="background-color:#fcfcfc;">
            <td><strong style="position:relative; float:right;">TOTAL: </strong>  </td>
            <td style="text-align: right;"><strong>{{ number_format($pedido->total, 2) }} MXN</strong></td>
        </tr>
    </table>

    @if ($index < $pedidos->count() - 1)
    <div class="page-break"></div>
    @endif
    @endforeach

    <!--<div id="footer">
        <div class="page-number"></div>
    </div>-->

    <script type="text/php">
        if (isset($pdf)) {
            $text = "Página {PAGE_NUM} de {PAGE_COUNT}";
            $size = 10;
            $font = $fontMetrics->getFont("Verdana");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 35;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>

</body>
</html>